import type { Catch, Lot, Quota, TenizUser, Zone } from "./types";

const now = new Date("2026-06-10T09:00:00+05:00");
const hoursAgo = (hours: number) =>
  new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();

export const demoUsers: TenizUser[] = [
  {
    id: "usr_fisherman_1",
    name: "Арман Сагындык",
    phone: "+7 701 225 44 10",
    role: "fisherman",
    created_at: hoursAgo(96),
  },
  {
    id: "usr_fisherman_2",
    name: "Марат Жанабай",
    phone: "+7 702 118 91 42",
    role: "fisherman",
    created_at: hoursAgo(84),
  },
  {
    id: "usr_buyer_1",
    name: "Aqtau Fish Market",
    phone: "+7 7292 55 13 77",
    role: "buyer",
    created_at: hoursAgo(80),
  },
  {
    id: "usr_inspector_1",
    name: "Инспектор Айдана",
    phone: "+7 701 700 80 20",
    role: "inspector",
    created_at: hoursAgo(70),
  },
];

export const demoCatches: Catch[] = [
  {
    id: "catch_001",
    fisherman_id: "usr_fisherman_1",
    fish_type: "судак",
    weight_kg: 18.4,
    size_cm: 44,
    photo_url: "/fish-demo.svg",
    latitude: 43.674,
    longitude: 51.172,
    is_legal: true,
    ai_verdict: {
      "вид": "судак",
      "размер_см": 44,
      "законно": true,
      "вердикт": "МОЖНО ПРОДАВАТЬ",
      "причина": "Судак больше минимального размера 38 см.",
    },
    quota_used: 18.4,
    qr_code: "TNZ-SDK-001",
    created_at: hoursAgo(1),
  },
  {
    id: "catch_002",
    fisherman_id: "usr_fisherman_1",
    fish_type: "вобла",
    weight_kg: 32.8,
    size_cm: 19,
    photo_url: "/fish-demo.svg",
    latitude: 43.735,
    longitude: 51.198,
    is_legal: true,
    ai_verdict: {
      "вид": "вобла",
      "размер_см": 19,
      "законно": true,
      "вердикт": "МОЖНО ПРОДАВАТЬ",
      "причина": "Вобла больше минимального размера 17 см.",
    },
    quota_used: 32.8,
    qr_code: "TNZ-VBL-002",
    created_at: hoursAgo(3),
  },
  {
    id: "catch_003",
    fisherman_id: "usr_fisherman_2",
    fish_type: "сазан",
    weight_kg: 21.2,
    size_cm: 46,
    photo_url: "/fish-demo.svg",
    latitude: 43.884,
    longitude: 51.284,
    is_legal: true,
    ai_verdict: {
      "вид": "сазан",
      "размер_см": 46,
      "законно": true,
      "вердикт": "МОЖНО ПРОДАВАТЬ",
      "причина": "Сазан больше минимального размера 40 см.",
    },
    quota_used: 21.2,
    qr_code: "TNZ-SZN-003",
    created_at: hoursAgo(5),
  },
  {
    id: "catch_004",
    fisherman_id: "usr_fisherman_2",
    fish_type: "осётр",
    weight_kg: 9.8,
    size_cm: 55,
    photo_url: "/fish-demo.svg",
    latitude: 44.19,
    longitude: 51.515,
    is_legal: false,
    ai_verdict: {
      "вид": "осётр",
      "размер_см": 55,
      "законно": false,
      "вердикт": "НУЖНО ОТПУСТИТЬ",
      "причина": "Осетр меньше минимального размера 60 см.",
    },
    quota_used: 0,
    qr_code: "TNZ-OST-004",
    created_at: hoursAgo(7),
  },
  {
    id: "catch_005",
    fisherman_id: "usr_fisherman_1",
    fish_type: "судак",
    weight_kg: 46.1,
    size_cm: 49,
    photo_url: "/fish-demo.svg",
    latitude: 44.435,
    longitude: 51.612,
    is_legal: true,
    ai_verdict: null,
    quota_used: 46.1,
    qr_code: "TNZ-SDK-005",
    created_at: hoursAgo(9),
  },
  {
    id: "catch_006",
    fisherman_id: "usr_fisherman_2",
    fish_type: "вобла",
    weight_kg: 15.5,
    size_cm: 18,
    photo_url: "/fish-demo.svg",
    latitude: 44.639,
    longitude: 51.406,
    is_legal: true,
    ai_verdict: null,
    quota_used: 15.5,
    qr_code: "TNZ-VBL-006",
    created_at: hoursAgo(11),
  },
  {
    id: "catch_007",
    fisherman_id: "usr_fisherman_1",
    fish_type: "сазан",
    weight_kg: 28.6,
    size_cm: 41,
    photo_url: "/fish-demo.svg",
    latitude: 44.84,
    longitude: 51.236,
    is_legal: true,
    ai_verdict: null,
    quota_used: 28.6,
    qr_code: "TNZ-SZN-007",
    created_at: hoursAgo(14),
  },
  {
    id: "catch_008",
    fisherman_id: "usr_fisherman_2",
    fish_type: "судак",
    weight_kg: 12.7,
    size_cm: 36,
    photo_url: "/fish-demo.svg",
    latitude: 45.02,
    longitude: 51.064,
    is_legal: false,
    ai_verdict: null,
    quota_used: 0,
    qr_code: "TNZ-SDK-008",
    created_at: hoursAgo(18),
  },
  {
    id: "catch_009",
    fisherman_id: "usr_fisherman_1",
    fish_type: "осётр",
    weight_kg: 6.9,
    size_cm: 67,
    photo_url: "/fish-demo.svg",
    latitude: 45.163,
    longitude: 50.923,
    is_legal: true,
    ai_verdict: null,
    quota_used: 6.9,
    qr_code: "TNZ-OST-009",
    created_at: hoursAgo(21),
  },
  {
    id: "catch_010",
    fisherman_id: "usr_fisherman_2",
    fish_type: "вобла",
    weight_kg: 52.3,
    size_cm: 20,
    photo_url: "/fish-demo.svg",
    latitude: 44.28,
    longitude: 50.84,
    is_legal: true,
    ai_verdict: null,
    quota_used: 52.3,
    qr_code: "TNZ-VBL-010",
    created_at: hoursAgo(23),
  },
];

export const demoLots: Lot[] = [
  {
    id: "lot_001",
    catch_id: "catch_001",
    fisherman_id: "usr_fisherman_1",
    price_per_kg: 3100,
    weight_kg: 18.4,
    status: "active",
    buyer_id: null,
    created_at: hoursAgo(0.8),
  },
  {
    id: "lot_002",
    catch_id: "catch_002",
    fisherman_id: "usr_fisherman_1",
    price_per_kg: 1180,
    weight_kg: 32.8,
    status: "active",
    buyer_id: null,
    created_at: hoursAgo(2.6),
  },
  {
    id: "lot_003",
    catch_id: "catch_003",
    fisherman_id: "usr_fisherman_2",
    price_per_kg: 1950,
    weight_kg: 21.2,
    status: "active",
    buyer_id: null,
    created_at: hoursAgo(4.5),
  },
  {
    id: "lot_004",
    catch_id: "catch_005",
    fisherman_id: "usr_fisherman_1",
    price_per_kg: 3300,
    weight_kg: 46.1,
    status: "active",
    buyer_id: null,
    created_at: hoursAgo(8.6),
  },
  {
    id: "lot_005",
    catch_id: "catch_009",
    fisherman_id: "usr_fisherman_1",
    price_per_kg: 8900,
    weight_kg: 6.9,
    status: "sold",
    buyer_id: "usr_buyer_1",
    created_at: hoursAgo(20.8),
  },
];

export const demoQuotas: Quota[] = [
  { id: "quota_1", fish_type: "сазан", total_kg: 1200, used_kg: 487, season_year: 2026 },
  { id: "quota_2", fish_type: "вобла", total_kg: 2200, used_kg: 1218, season_year: 2026 },
  { id: "quota_3", fish_type: "судак", total_kg: 980, used_kg: 642, season_year: 2026 },
  { id: "quota_4", fish_type: "осётр", total_kg: 120, used_kg: 88, season_year: 2026 },
];

export const demoZones: Zone[] = [
  { id: "zone_1", name: "Актау порт", latitude: 43.65, longitude: 51.16, risk_level: 3 },
  { id: "zone_2", name: "Форт-Шевченко", latitude: 44.51, longitude: 50.26, risk_level: 5 },
  { id: "zone_3", name: "Кендерли", latitude: 42.51, longitude: 52.05, risk_level: 4 },
  { id: "zone_4", name: "Северная линия", latitude: 45.08, longitude: 51.05, risk_level: 8 },
];

export function activeLotsWithDetails() {
  return demoLots
    .filter((lot) => lot.status === "active")
    .map((lot) => ({
      ...lot,
      catch: demoCatches.find((catchItem) => catchItem.id === lot.catch_id)!,
      fisherman: demoUsers.find((user) => user.id === lot.fisherman_id)!,
    }));
}
